In [76]:
%pip install pandas==1.5.1
%pip install torchmetrics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [77]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [78]:
import torch
from torch import nn, optim
from torch.autograd.variable import Variable
from torchvision import transforms, datasets
from torchvision.transforms.functional import hflip
from torch.utils.data import Dataset,DataLoader
from torch.optim import Adam
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pickle
from matplotlib import image as mpimg
import re
from PIL import Image
import pandas as pd
import datetime
from torchmetrics import TweedieDevianceScore

import math
from torch import default_generator, randperm
from torch._utils import _accumulate
from torch.utils.data.dataset import Subset

from sklearn.metrics import fbeta_score, make_scorer, mean_poisson_deviance
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from IPython.display import display
from sklearn import metrics
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
import sklearn
from sklearn.metrics import mean_squared_error
from sklearn.metrics import fbeta_score, make_scorer



In [83]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

PATH='/content/drive/MyDrive/MLproject/'

with open(PATH+"listings.pkl", "rb") as fh:
    data = pickle.load(fh)
with open(PATH+"test_listings_image.pkl", "rb") as fh:
    data_test = pickle.load(fh)

cuda


# Dataset

In [84]:
data.columns

Index(['Are Pets Allowed', 'Category Idx', 'Day of Advertisement Created',
       'Day of Date Available From', 'Demand', 'Floor', 'Geo Canton',
       'Geo City', 'Geo Zip', 'Has Balcony', 'Has Cabletv', 'Has Elevator',
       'Has Fireplace', 'Has Garage', 'Has Parking', 'Is New Construction',
       'Is New Construction Potential', 'Is Tenant2Tenant',
       'Is Wheelchairaccessible', 'Jahr', 'Leerwohnungsziffer',
       'Listing Description', 'Listing Title', 'Livingspace',
       'Number Of Rooms', 'Number Of Rooms Cleaned', 'Number of Documents',
       'Number of Images', 'Price Extra Normalized', 'Price Gross Normalized',
       'Price M2 Normalized', 'Price Net Normalized', 'Property Reference Id',
       'Size M2 Normalized', 'Subcategory En Idx', 'Year Built',
       'Year Lastrenovated'],
      dtype='object')

In [85]:
data.sample(5)


Are Pets Allowed Category Idx Day of Advertisement Created  \
1010              True         APPT            February 11, 2019   
4754               NaN         APPT                July 15, 2019   
17504            False         APPT                 July 4, 2017   
19173             True         APPT             January 11, 2019   
19719              NaN         APPT             January 25, 2021   

      Day of Date Available From  Demand  Floor Geo Canton       Geo City  \
1010                 May 1, 2019    14.0    1.0         ZH      Wädenswil   
4754             October 1, 2019    14.0    1.0         ZH         Zürich   
17504            October 1, 2017     0.0    0.0         ZH         Kloten   
19173              April 1, 2019    33.0    1.0         BE           Bern   
19719                May 1, 2021     3.0    2.0         AG  Münchwilen AG   

       Geo Zip Has Balcony  ... Number of Images Price Extra Normalized  \
1010      8820         NaN  ...                5                   70.0   
4754      8050         NaN  ...                4                   70.0   
17504     8302       False  ...                7                  380.0   
19173     3013         NaN  ...                4                   80.0   
19719     4333         NaN  ...               13                  320.0   

      Price Gross Normalized Price M2 Normalized Price Net Normalized  \
1010                  1885.0                26.0               1815.0   
4754                  2010.0                33.0               1940.0   
17504                 2160.0                21.0               1780.0   
19173                  750.0                30.0                670.0   
19719                 2490.0                15.0               2170.0   

      Property Reference Id  Size M2 Normalized  Subcategory En Idx  \
1010           9792.22.9380                72.0           Apartment   
4754           5111.61.9723                61.0           Apartment   
17504          0664.76.5829               105.0           Apartment   
19173          1343.50.3115                25.0           Apartment   
19719          5168.34.0065               162.0           Apartment   

      Year Built  Year Lastrenovated  
1010         NaN                 NaN  
4754         NaN                 NaN  
17504        NaN                 NaN  
19173        NaN                 NaN  
19719     2011.0              2011.0  

[5 rows x 37 columns]

In [86]:
features = data[['Are Pets Allowed', 'Category Idx', 'Day of Advertisement Created',
       'Day of Date Available From', 'Floor', 'Geo Canton',
       'Geo City', 'Geo Zip', 'Has Balcony', 'Has Cabletv', 'Has Elevator',
       'Has Fireplace', 'Has Garage', 'Has Parking', 'Is New Construction',
       'Is New Construction Potential', 'Is Tenant2Tenant',
       'Is Wheelchairaccessible', 'Jahr', 'Leerwohnungsziffer',
       'Listing Description', 'Listing Title', 'Livingspace',
       'Number Of Rooms', 'Number Of Rooms Cleaned', 'Number of Documents',
       'Number of Images', 'Price Extra Normalized', 'Price Gross Normalized',
       'Price M2 Normalized', 'Price Net Normalized', 'Property Reference Id',
       'Size M2 Normalized', 'Subcategory En Idx', 'Year Built',
       'Year Lastrenovated']]

label = data['Demand']


In [87]:
def accuracy(y_pred,y,tol=0):
    numpy_y=y.to_numpy()
    rounded_y_pred=y_pred.round()
    assert len(rounded_y_pred)==len(numpy_y)
    return (np.abs(rounded_y_pred-numpy_y)<=tol).sum()/len(rounded_y_pred)


def evaluate_model(y_true,y_pred):
    prediction=y_pred.copy()
    prediction[prediction<=0]=10**(-10)
    return mean_poisson_deviance(y_true,prediction)
    

scoring=make_scorer(evaluate_model,greater_is_better=False)




In [88]:
seed=np.random.randint(100)
DICT_GEO_CANTON={'ZH':0, 'VD':1, 'BE':2, 'AG':3, 'FR':4, 'SG':5, 'LU':6, 'SO':7, 'SH':8, 'GE':9, 'VS':10,
       'SZ':11, 'BS':12, 'ZG':13, 'BL':14, 'NE':15, 'TI':16, 'GR':17, 'TG':18, 'AR':19, 'UR':20, 'GL':21,
       'NW':22, 'JU':22}

DICT_SUBCATEGORY={'Apartment':0, 'Duplex':1, 'Row house':2, 'Roof flat':3, 'Attic flat':4,
       'Single house':5, 'Single Room':6, 'Studio':7, 'Furnished dwelling':8,
       'Loft':9, 'Mansard':10, 'Farm house':11}


#identifying the boolean variables
bool_features=['Are Pets Allowed', 'Has Balcony', 'Has Cabletv',
               'Has Elevator', 'Has Fireplace', 'Has Garage',
               'Has Parking', 'Is New Construction', 'Is New Construction Potential', 
               'Is Tenant2Tenant', 'Is Wheelchairaccessible']
print(bool_features)
data_bool=data[bool_features]


#The ordinal features are:
ordinal_features=['Floor','Livingspace', 'Number Of Rooms',
       'Number Of Rooms Cleaned', 'Number of Documents', 'Number of Images',
       'Price Extra Normalized', 'Price Gross Normalized',
       'Price M2 Normalized', 'Price Net Normalized', 
       'Size M2 Normalized', 'Year Built',
       'Year Lastrenovated']

categorical_features={'Geo Canton':DICT_GEO_CANTON,'Subcategory En Idx':DICT_SUBCATEGORY}

#Which leaves us with 'Property Reference Id ',Listing Description' and 'Listing Title' which we will not use for regression purpose
data=data.drop(['Property Reference Id','Listing Description','Listing Title'],axis=1)

null_count=pd.concat([data.isnull().sum().rename('NaN train set'),data_test.isnull().sum().rename('NaN test set')],axis=1)

iter_imputer = IterativeImputer(estimator=ExtraTreesRegressor(n_estimators=10, random_state=0),random_state=42,max_iter=20)

temp=data.copy()

iter_imputed = iter_imputer.fit_transform(data[ordinal_features])

temp.loc[:,ordinal_features]=iter_imputed




['Are Pets Allowed', 'Has Balcony', 'Has Cabletv', 'Has Elevator', 'Has Fireplace', 'Has Garage', 'Has Parking', 'Is New Construction', 'Is New Construction Potential', 'Is Tenant2Tenant', 'Is Wheelchairaccessible']


/usr/local/lib/python3.8/dist-packages/sklearn/impute/_iterative.py:699: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
<ipython-input-88-cca028cf8e98>:41: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  temp.loc[:,ordinal_features]=iter_imputed


In [89]:

#Deal with 'Day of Advertisement Created' and 'Day of Date Available From'
def compute_diff_date(X: pd.DataFrame, y=None):
    X_copy=X.copy()
    threshold=datetime.datetime(2022,9,1)
    X_copy['Days Between September and Created']=pd.to_datetime(X_copy['Day of Advertisement Created']).apply(lambda x:(threshold-x).days)
    X_copy['Days Between September and Available']=pd.to_datetime(X_copy['Day of Date Available From']).apply(lambda x:(threshold-x).days)                                                           
    X_copy.drop(['Day of Advertisement Created','Day of Date Available From'],axis=1,inplace=True)
    return X_copy

diff_date_transformer = FunctionTransformer(compute_diff_date)

print('Dealing with date')
display(diff_date_transformer.transform(data))

Dealing with date


Are Pets Allowed Category Idx  Demand  Floor Geo Canton  \
0                  NaN         APPT    25.0    0.0         ZH   
1                  NaN         APPT     2.0    1.0         VD   
2                False         APPT     0.0    1.0         BE   
3                 True         APPT     4.0    1.0         AG   
4                False         APPT     3.0    0.0         FR   
...                ...          ...     ...    ...        ...   
19995            False         APPT     2.0    2.0         SG   
19996             True         APPT     1.0    2.0         VD   
19997              NaN         APPT     2.0    5.0         GE   
19998              NaN         APPT     2.0    7.0         VD   
19999            False         APPT     3.0    0.0         TG   

                   Geo City  Geo Zip Has Balcony Has Cabletv Has Elevator  \
0                 Dübendorf     8600         NaN         NaN          NaN   
1      Le Mont-sur-Lausanne     1052         NaN         NaN          NaN   
2                Langenthal     4900       False       False        False   
3                Fislisbach     5442         NaN        True          NaN   
4                     Bulle     1630       False       False        False   
...                     ...      ...         ...         ...          ...   
19995            St. Gallen     9000       False       False        False   
19996                 Vevey     1800         NaN        True         True   
19997                 Lancy     1212         NaN         NaN          NaN   
19998                  Nyon     1260         NaN         NaN          NaN   
19999            Frauenfeld     8500       False        True         True   

       ... Price Extra Normalized Price Gross Normalized Price M2 Normalized  \
0      ...                  550.0                 4460.0                19.0   
1      ...                  120.0                 1345.0                30.0   
2      ...                  250.0                 1570.0                15.0   
3      ...                  270.0                 1480.0                17.0   
4      ...                  300.0                 1490.0                19.0   
...    ...                    ...                    ...                 ...   
19995  ...                  170.0                 1350.0                15.0   
19996  ...                  190.0                 1940.0                23.0   
19997  ...                  275.0                 2175.0                32.0   
19998  ...                  240.0                 3540.0                37.0   
19999  ...                  130.0                  845.0                16.0   

      Price Net Normalized  Size M2 Normalized  Subcategory En Idx Year Built  \
0                   3910.0               232.0           Apartment     2016.0   
1                   1225.0                45.0           Apartment        NaN   
2                   1320.0               103.0           Apartment        NaN   
3                   1210.0                86.0           Apartment     1985.0   
4                   1190.0                79.0           Apartment        NaN   
...                    ...                 ...                 ...        ...   
19995               1180.0                90.0           Apartment        NaN   
19996               1750.0                84.0           Apartment     1968.0   
19997               1900.0                68.0           Apartment        NaN   
19998               3300.0                95.0           Apartment        NaN   
19999                715.0                52.0           Apartment        NaN   

       Year Lastrenovated Days Between September and Created  \
0                  2016.0                                602   
1                     NaN                               1018   
2                     NaN                               1996   
3                  1985.0                                421   
4                     NaN                     

In [90]:
other_categorical_features=['Category Idx','Geo City','Geo Zip']
data=data.drop(other_categorical_features,axis=1)

In [91]:
categorical_features={'Geo Canton':DICT_GEO_CANTON,'Subcategory En Idx':DICT_SUBCATEGORY}


In [92]:
def fill_nan(X: pd.DataFrame,bool_features,categorical_features,ordinal_features,bool_fill=-99999, y=None):
    df=X.copy() #We don't want to modify the dataset
    
    #Dealing with categorical values
    for bool_feature in bool_features:
        df.loc[:,bool_feature]=df.loc[:,bool_feature].fillna(bool_fill)
        df.loc[df[bool_feature] == False, bool_feature] = 0
        df.loc[data[bool_feature] == True, bool_feature] = 1
    
    #Dealing with ordinal values
    for ordinal_feature in ordinal_features:
        df[ordinal_feature].fillna(df[ordinal_feature].mean(),inplace=True)
        
    #Dealing with categorical features
    for categorical_feature in categorical_features.keys():
        dict_replace=categorical_features[categorical_feature]
        df[categorical_feature]=df[categorical_feature].replace(dict_replace)
        df[categorical_feature].fillna(len(dict_replace)+1,inplace=True)
        #df[categorical_feature].fillna(bool_fill,inplace=True)
    return df

na_fill_estimator = FunctionTransformer(fill_nan,kw_args={'bool_features':bool_features,
                                                          'categorical_features':categorical_features,
                                'ordinal_features':ordinal_features+['Days Between September and Created',
                                                                     'Days Between September and Available']})


features_to_encode=bool_features
col_trans = make_column_transformer(
                        (OneHotEncoder(),features_to_encode),
                        remainder = "passthrough"
                        )
print('One Hot Encoded data:')
print(col_trans.fit_transform(na_fill_estimator.transform(diff_date_transformer.transform(data))))
print(col_trans.fit_transform(na_fill_estimator.transform(diff_date_transformer.transform(data))).shape)



One Hot Encoded data:
[[1.0 0.0 0.0 ... 2016.0 602 549.0]
 [1.0 0.0 0.0 ... 1991.7910962715637 1018 914.0]
 [0.0 1.0 0.0 ... 1991.7910962715637 1996 1028.099604743083]
 ...
 [1.0 0.0 0.0 ... 1991.7910962715637 321 442.0]
 [1.0 0.0 0.0 ... 1991.7910962715637 700 488.0]
 [0.0 1.0 0.0 ... 1991.7910962715637 1939 1826.0]]
(20000, 51)


In [93]:
binary_features = ['Are Pets Allowed', 'Has Balcony', 'Has Cabletv', 'Has Elevator',
                  'Has Fireplace', 'Has Garage', 'Has Parking', 'Is New Construction',
                  'Is New Construction Potential', 'Is Tenant2Tenant',
                  'Is Wheelchairaccessible']
for column in binary_features:
  data.loc[data[column] == False, column] = 0
  data.loc[data[column] == True, column] = 1

data = pd.get_dummies(data, prefix=['Geo'], columns=['Geo Canton'])

data['Year Lastrenovated'].fillna(0, inplace = True)

data['Leerwohnungsziffer'] = pd.to_numeric(data['Leerwohnungsziffer'])
data['Jahr'] = pd.to_numeric(data['Jahr'])


In [109]:
output_cols = list(data['Demand'])


input_cols = data[['Are Pets Allowed', 'Floor',
       'Has Balcony', 'Has Cabletv', 'Has Elevator',
       'Has Fireplace', 'Has Garage', 'Has Parking', 'Is New Construction',
       'Is New Construction Potential', 'Is Tenant2Tenant',
       'Is Wheelchairaccessible', 'Livingspace', 'Number Of Rooms', 'Number Of Rooms Cleaned',
       'Number of Documents', 'Number of Images', 'Price Extra Normalized',
       'Price Gross Normalized', 'Price M2 Normalized', 'Price Net Normalized', 'Size M2 Normalized', 
       'Year Lastrenovated', 'Leerwohnungsziffer', 'Jahr',
       'Geo_AG', 'Geo_AR', 'Geo_BE', 'Geo_BL', 'Geo_BS', 'Geo_FR', 'Geo_GE', 
       'Geo_GL', 'Geo_GR', 'Geo_JU', 'Geo_LU', 'Geo_NE', 'Geo_NW', 'Geo_SG', 
       'Geo_SH', 'Geo_SO', 'Geo_SZ', 'Geo_TG', 'Geo_TI', 'Geo_UR', 'Geo_VD', 'Geo_VS', 'Geo_ZG', 'Geo_ZH']]

# Normalization of feature columns

def mean_norm(df_input):
    return df_input.apply(lambda x: (x-x.mean())/ x.std(), axis=0)

input_cols_norm = mean_norm(input_cols)
input_cols_norm.fillna(input_cols_norm.median(), inplace=True)
input_cols_norm.sample(10)

Are Pets Allowed     Floor  Has Balcony  Has Cabletv  Has Elevator  \
14812         -0.832208  2.648604    -0.200172     0.758779      0.798902   
13646          1.201510 -0.138449    -0.200172     0.758779      0.798902   
2162          -0.832208  1.255078    -0.200172     0.758779      0.798902   
13295         -0.832208  0.790569    -0.200172     0.758779      0.798902   
18634         -0.832208  0.326060    -0.200172     0.758779      0.798902   
9088           1.201510  2.184095    -0.200172     0.758779      0.798902   
16439         -0.832208 -0.138449    -0.200172    -1.317803     -1.251618   
10944         -0.832208 -0.138449    -0.200172     0.758779      0.798902   
7490          -0.832208 -0.602958    -0.200172    -1.317803     -1.251618   
5657          -0.832208 -0.602958    -0.200172    -1.317803     -1.251618   

       Has Fireplace  Has Garage  Has Parking  Is New Construction  \
14812      -0.156072    0.899897    -0.916588            -0.079381   
13646      -0.156072    0.899897    -0.916588            -0.079381   
2162       -0.156072    0.899897     1.090902            -0.079381   
13295      -0.156072    0.899897    -0.916588            -0.079381   
18634      -0.156072    0.899897    -0.916588            -0.079381   
9088       -0.156072    0.899897    -0.916588            -0.079381   
16439      -0.156072   -1.111143    -0.916588            -0.079381   
10944      -0.156072    0.899897    -0.916588            -0.079381   
7490       -0.156072   -1.111143    -0.916588            -0.079381   
5657       -0.156072   -1.111143    -0.916588            -0.079381   

       Is New Construction Potential  ...     Geo_SH    Geo_SO    Geo_SZ  \
14812                      -0.125677  ...  -0.099737 -0.196833 -0.097148   
13646                      -0.125677  ...  -0.099737 -0.196833 -0.097148   
2162                       -0.125677  ...  -0.099737 -0.196833 -0.097148   
13295                      -0.125677  ...  -0.099737 -0.196833 -0.097148   
18634                      -0.125677  ...  -0.099737 -0.196833 -0.097148   
9088                       -0.125677  ...  -0.099737 -0.196833 -0.097148   
16439                      -0.125677  ...  -0.099737 -0.196833 -0.097148   
10944                      -0.125677  ...  10.025857 -0.196833 -0.097148   
7490                       -0.125677  ...  -0.099737 -0.196833 -0.097148   
5657                       -0.125677  ...  -0.099737 -0.196833 -0.097148   

         Geo_TG    Geo_TI    Geo_UR    Geo_VD    Geo_VS   Geo_ZG    Geo_ZH  
14812 -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473 -0.723488  
13646 -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473  1.382123  
2162  -0.132288 -0.147698 -0.051055  3.851567 -0.104974 -0.10473 -0.723488  
13295 -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473  1.382123  
18634 -0.132288 -0.147698 -0.051055  3.851567 -0.104974 -0.10473 -0.723488  
9088  -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473 -0.723488  
16439 -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473 -0.723488  
10944 -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473 -0.723488  
7490  -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473 -0.723488  
5657  -0.132288 -0.147698 -0.051055 -0.259622 -0.104974 -0.10473  1.382123  

[10 rows x 49 columns]

# Data to tensors

In [110]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, random_split
from torch.autograd import Variable
import torchvision.models as models

In [111]:
inputs_array, targets_array1 = np.array(input_cols_norm.to_numpy()), label.to_numpy()
targets_array=[]
#We add brakets for tensor structure... (can be done differently)
for elt in targets_array1:
    targets_array.append([elt])
targets_array = np.array(targets_array)

print(type(inputs_array))
print(type(targets_array))
print(inputs_array)
print(targets_array)

inputs = torch.from_numpy(inputs_array).to(torch.float32)
targets = torch.from_numpy(targets_array).to(torch.float32)
dataset = TensorDataset(inputs, targets)

print(dataset)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[-0.83220833 -1.06746644 -0.20017178 ... -0.10497413 -0.10473044
   1.3821235 ]
 [-0.83220833 -0.60295764 -0.20017178 ... -0.10497413 -0.10473044
  -0.72348817]
 [-0.83220833 -0.60295764 -0.20017178 ... -0.10497413 -0.10473044
  -0.72348817]
 ...
 [-0.83220833  1.25507753 -0.20017178 ... -0.10497413 -0.10473044
  -0.72348817]
 [-0.83220833  2.18409511 -0.20017178 ... -0.10497413 -0.10473044
  -0.72348817]
 [-0.83220833 -1.06746644 -0.20017178 ... -0.10497413 -0.10473044
  -0.72348817]]
[[25.]
 [ 2.]
 [ 0.]
 ...
 [ 2.]
 [ 2.]
 [ 3.]]


In [112]:
VAL_PERCENT = 0.2
NUM_ROWS = int(len(data))
val_size = int(NUM_ROWS * VAL_PERCENT)
train_size = NUM_ROWS - val_size

train_ds, val_ds = random_split(dataset, [train_size, val_size])

print(len(train_ds), len(val_ds))

16000 4000


In [113]:
BATCH_SIZE = 128

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE)

for xb, yb, in train_loader:
    print("inputs:", xb)
    print("targets:", yb)
    break

inputs: tensor([[-0.8322,  0.3261, -0.2002,  ..., -0.1050, -0.1047, -0.7235],
        [-0.8322, -1.0675, -0.2002,  ..., -0.1050, -0.1047,  1.3821],
        [-0.8322, -0.6030, -0.2002,  ..., -0.1050, -0.1047, -0.7235],
        ...,
        [-0.8322,  0.7906, -0.2002,  ..., -0.1050, -0.1047, -0.7235],
        [ 1.2015, -0.1384, -0.2002,  ..., -0.1050, -0.1047,  1.3821],
        [-0.8322, -1.0675, -0.2002,  ..., -0.1050, -0.1047,  1.3821]])
targets: tensor([[ 0.],
        [15.],
        [ 1.],
        [ 9.],
        [ 1.],
        [ 2.],
        [20.],
        [ 7.],
        [ 0.],
        [ 3.],
        [ 6.],
        [12.],
        [ 3.],
        [ 0.],
        [ 1.],
        [11.],
        [ 0.],
        [ 5.],
        [ 0.],
        [ 0.],
        [ 1.],
        [ 0.],
        [11.],
        [ 1.],
        [ 8.],
        [ 1.],
        [ 5.],
        [ 3.],
        [ 6.],
        [ 1.],
        [ 0.],
        [ 2.],
        [ 1.],
        [ 1.],
        [ 2.],
        [61.],
        [

# Model


In [114]:
#Creation of linear regression model

in_cols = input_cols.columns
out_cols = ['Demand']

input_size = len(in_cols)
output_size = len(out_cols)

class PredictModel(nn.Module):


    def __init__(self):
        # super().__init__()
        # self.linear = nn.Linear(input_size, output_size)
        super(PredictModel, self).__init__()
        self.layer_1 = nn.Linear(input_size, 16)
        self.layer_2 = nn.Linear(16, 32)
        self.layer_3 = nn.Linear(32, 64)
        # self.layer_4 = nn.Linear(64, 128)
        # self.layer_5 = nn.Linear(128, 64)
        self.layer_4 = nn.Linear(64, 32)
        self.layer_5 = nn.Linear(32, 16)
        self.layer_out = nn.Linear(16, output_size)
        
        self.relu = nn.ReLU()
    
    def forward(self, xb):
        # out = self.linear(xb)
        x = self.relu(self.layer_1(xb))
        x = self.relu(self.layer_2(x))
        x = self.relu(self.layer_3(x))
        x = self.relu(self.layer_4(x))
        x = self.relu(self.layer_5(x))
        # x = self.relu(self.layer_6(x))
        # x = self.relu(self.layer_7(x))
        x = self.layer_out(x)
        return x


    def training_step(self, batch):
        inputs, targets = batch
        out = self(inputs)
        loss = F.l1_loss(out, targets)
        return loss
    
    def validation_step(self, batch):
        inputs, targets = batch
        out = self(inputs)
        loss = F.l1_loss(out, targets)
        return {'val_loss': loss.detach()}
    
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()
        return {'val_loss': epoch_loss.item()}
    
    def epoch_end(self, epoch, result, num_epochs):
        if (epoch+1) % 20 == 0 or epoch == num_epochs - 1:
            print("Epoch[{}], val_loss: {:.4f}".format(epoch+1, result['val_loss']))

In [115]:
#Defining our model 
model = PredictModel()
list(model.parameters())

#Training loop
def evaluate(model, val_loader):
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    history=[]
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result, epochs)
        history.append(result)
    return history

result = evaluate(model, val_loader)
print(result)




{'val_loss': 8.67424488067627}


In [116]:
epochs = 300
lr = 0.001
history = fit(epochs, lr, model, train_loader, val_loader)

Epoch[20], val_loss: 7.6849
Epoch[40], val_loss: 7.6089
Epoch[60], val_loss: 7.5226
Epoch[80], val_loss: 6.3333
Epoch[100], val_loss: 6.0890
Epoch[120], val_loss: 5.9972
Epoch[140], val_loss: 5.9100
Epoch[160], val_loss: 5.8137
Epoch[180], val_loss: 5.7341
Epoch[200], val_loss: 5.6661
Epoch[220], val_loss: 5.5873
Epoch[240], val_loss: 5.4945
Epoch[260], val_loss: 5.4427
Epoch[280], val_loss: 5.3997
Epoch[300], val_loss: 5.4052


In [117]:
# We try to test our model on a random value of the test set

def predict_single(input, model):
    inputs = input.unsqueeze(0)
    predictions = model(inputs)         
    prediction = predictions[0].detach()
    return prediction

input, target = val_ds[50]
prediction = predict_single(input, model)

print("Input:", input)
print("Target:", target)
print("Prediction:", prediction)
print()


# Return the entire predictions (Tensor Y_label)

def predict_all(val_ds, model):
    predictions = []
    targets = []
    for i in range(len(val_ds)):
       input, target = val_ds[i]
       prediction = predict_single(input, model)
       predictions.append(prediction.numpy()[0])
       targets.append(target)
    return predictions, targets

predictions, targets = predict_all(val_ds, model)

#On arrondi à l'entier le plus proche pour effectuer notre prédiction et on remplace les valeurs négatives
# predictions = np.round(predictions)
predictions = [max(10**(-0.05),k) for k in predictions]

# print(predictions)
# print(targets)


Input: tensor([-0.8322, -1.0675, -0.2002, -1.3178, -1.2516, -0.1561, -1.1111, -0.9166,
        -0.0794, -0.1257, -0.1090, -0.0535, -0.7679, -0.7491, -0.7491,  0.6735,
        -1.6900, -0.6478, -1.0284, -0.1149, -1.0179, -0.7682, -0.9030,  2.8410,
        -1.3000,  2.8108, -0.0490, -0.2556, -0.2370, -0.1906, -0.1600, -0.2108,
        -0.0436, -0.0723, -0.0122, -0.2217, -0.1367, -0.0464, -0.2688, -0.0997,
        -0.1968, -0.0971, -0.1323, -0.1477, -0.0511, -0.2596, -0.1050, -0.1047,
        -0.7235])
Target: tensor([0.])
Prediction: tensor([2.7002])



In [118]:
#Computation of the accurcy of our model on test set
EPSILON = 2

def accuracy(val_ds, model, EPSILON):
    corrects = 0
    for i in range(len(val_ds)):
        input, target = val_ds[i]
        prediction = predict_single(input, model)
        prediction = np.round(prediction)
        if prediction <= target + EPSILON and prediction >= target - EPSILON:
            corrects+=1
    accuracy = corrects/len(val_ds)
    print("Accuracy for EPSILON={}:".format(EPSILON), accuracy)
    return accuracy

accuracy(val_ds, model, EPSILON)



#Using Mean Poisson deviance
from sklearn.metrics import mean_poisson_deviance

print("Mean Poisson deviance:", mean_poisson_deviance(targets, predictions))




Accuracy for EPSILON=2: 0.55625
Mean Poisson deviance: 6.915119495121968


/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:746: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  array = np.asarray(array, order=order, dtype=dtype)
